# Generated by Django 3.0.4 on 2020-03-12 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_edithorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edithor1al',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Edithorial'),
        ),
    ]
