# Generated by Django 3.0.4 on 2020-03-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_edithor1al'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='edithor1al',
            new_name='edithorial_id',
        ),
    ]
