# Generated by Django 3.0.4 on 2020-03-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200316_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='edithorial_id',
            new_name='Edithorial',
        ),
    ]
