# Generated by Django 3.0.4 on 2020-03-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200316_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Edithorial',
            new_name='edithorial',
        ),
    ]
